### ISSUE TITLE
module hang up

### ISSUE THREAD

**Issue by ostfilinchen** [ChristianGeie/MMM-PublicTransportVVO#1] opened 2017-08-17 11:34 UTC
Hi,

the module works fine, but if there is no data, like in the night, the module Shows me the same Data as the last Data from yesterday. So the module didn't update the Data.

Can u please check this?

Regards
Daniel

**Comment by ChristianGeie** [comment] 2017-08-24 06:04
Hi Daniel,
the module updates all data every 30 sec. so i think if your station has no departures, no data should be show on your magic mirror. Can you provide me a screenshot or anything else, so i can reproduce this issue? thanks a lot.
Christian

**Comment by ostfilinchen** [comment] 2017-08-24 13:43
Hi Christian,

here is my config:

{
module: 'MMM-PublicTransportVVO',
position: 'top_right',
config: {
stationId: 33006201, //Bahnhof
colored: true,
fade: false,
delay: 20,
initialLoadDelay: 10,
updateInterval: 30000,
marqueeLongDirections: true,
showColoredLineSymbols: true,
showTableHeaders: false,
showTableHeadersAsSymbols: false,
maxReachableDepartures: 3
}
},
I hope it helps you to reproduce the error.

Daniel

Am 24.08.2017 08:04 schrieb "ChristianGeie" <notifications@github.com>:

**Comment by ChristianGeie** [comment] 2017-08-24 21:57
Hi Daniel,
i can reproduce the issue with your station id. with my last commit i added a function to handle stations with empty departures. pls check it out.

Christian

**Comment by ostfilinchen** [comment] 2017-08-25 12:44
Hi Christian,

i have updated the modul this morning. I'll give u a Response tomorrow.

Daniel

**Comment by ostfilinchen** [comment] 2017-08-26 07:05
Hi Christian.

Good news. Now it works for me.

Thanks
Daniel

**Comment by ChristianGeie** [comment] 2017-08-27 11:52
I also think the problem is fixed, soi close this issue

**Closed by ChristianGeie** 2017-08-27 11:52 UTC
Labels: bug
